train <- read.csv("train.csv")
test <- read.csv("test.csv")
# train1$income <-factor(train1$income, levels = levels(test1$income))
# levels(train1$income)
model1 <- glm(Ch1~segment+money+year+miles+night+gender+age+educ+region+Urb+ppark, data = train, family = binomial)
pred1 <- predict(model1, newdata = train, type = "response")
predtest1 <- predict(model1, newdata = test, type = "response")
model2 <- glm(Ch2~segment+money+year+miles+night+gender+age+educ+region+Urb+ppark, data = train, family = binomial)
pred2<- predict(model2, newdata = train, type = "response")
predtest2<- predict(model2, newdata = test, type = "response")
model3 <- glm(Ch3~segment+money+year+miles+night+gender+age+educ+region+Urb+ppark, data = train, family = binomial)
pred3<- predict(model3, newdata = train, type = "response")
predtest3<- predict(model3, newdata = test, type = "response")
model4 <- glm(Ch4~segment+money+year+miles+night+gender+age+educ+region+Urb+ppark, data = train, family = binomial)
pred4<- predict(model4, newdata = train, type = "response")
predtest4<- predict(model4, newdata = test, type = "response")
pred1 <- as.matrix(pred1)
pred2 <- as.matrix(pred2)
pred3 <- as.matrix(pred3)
pred4 <- as.matrix(pred4)
predtest1 <- as.matrix(predtest1)
predtest2 <- as.matrix(predtest2)
predtest3 <- as.matrix(predtest3)
predtest4 <- as.matrix(predtest4)
pred <- cbind(pred1, pred2)
pred <- cbind(pred, pred3)
pred <- cbind(pred, pred4)
predtest <- cbind(predtest1, predtest2, predtest3, predtest4)
colnames(pred) <- c("pred1","pred2","pred3","pred4")
colnames(predtest) <- c("pred1","pred2","pred3","pred4")
summary(model1)
model1 <- glm(Ch1~segment+miles+night+educ+region+Urb, data = train, family = binomial)
pred1 <- predict(model1, newdata = train, type = "response")
predtest1 <- predict(model1, newdata = test, type = "response")
model2 <- glm(Ch2~segment+miles+night+educ+region+Urb, data = train, family = binomial)
pred2<- predict(model2, newdata = train, type = "response")
predtest2<- predict(model2, newdata = test, type = "response")
model3 <- glm(Ch3~segment+miles+night+educ+region+Urb, data = train, family = binomial)
pred3<- predict(model3, newdata = train, type = "response")
predtest3<- predict(model3, newdata = test, type = "response")
model4 <- glm(Ch4~segment+miles+night+educ+region+Urb, data = train, family = binomial)
pred4<- predict(model4, newdata = train, type = "response")
predtest4<- predict(model4, newdata = test, type = "response")
